---
title: "Subset Pericardial T Cells"
author: "Nadine"
date: "2026-04-16"
output: 
html_document:
  self_contained: no
  code_folding: show
  number_sections: no
  toc: yes
  toc_depth: 3
  toc_float: true
  collapsed: no
  smooth_scroll: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

# Load packages
```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(ggpubr)
  library(dplyr)
  library(ggplot2)
  library(here)
})
```


# Load seurat object
```{r}
# Load merged and cleaned object
basedir<- here()
fileNam <- paste0(basedir, "/data/pericarditis_allmerged_cleaned_cL_seurat.rds")
seuratM <- readRDS(fileNam)
```


# Subset T cells
```{r}
unique(seuratM$clusterLabel)
Idents(seuratM) <- seuratM$clusterLabel
seuratT <- subset(seuratM, idents = c("Tcells", "gdTcells"))
dim(seuratT)
```


# Rerun normalization
```{r}
seuratT <- NormalizeData(object = seuratT)
seuratT <- FindVariableFeatures(object = seuratT)
seuratT <- ScaleData(object = seuratT, verbose = FALSE)
seuratT <- RunPCA(object=seuratT, npcs=30, verbose = FALSE)
seuratT <- RunTSNE(object = seuratT, reduction = "pca", dims=1:20)
seuratT <- RunUMAP(object = seuratT, reduction = "pca", dims = 1:20)
seuratT <- FindNeighbors(object = seuratT, reduction = "pca", dims = 1:20)
res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratT <-FindClusters(object = seuratT, resolution = res[i],
                        random.seed = 1234)
}
```


## DimPlot Clusters {.tabset}

### Resolution 0.25
```{r}
Idents(seuratT) <-  seuratT$RNA_snn_res.0.25
DimPlot(seuratT, reduction = "umap", label = T)
```

### Resolution 0.4
```{r}
Idents(seuratT) <-  seuratT$RNA_snn_res.0.4
DimPlot(seuratT, reduction = "umap", label = T)
```


# Marker genes per cluster
```{r, include = T, eval = T}
# Set identity to resolution 0.25
Idents(seuratT) <-  seuratT$RNA_snn_res.0.25

# Run marker genes
seuratT_markers_all <- FindAllMarkers(object = seuratT, assay ="RNA",
                                     only.pos = TRUE, min.pct = 0.25,
                                     logfc.threshold = 0.25,
                                     test.use = "wilcox")

# Save marker genes as text file
basedir<- here()
basedir <- paste0(basedir, "/docs/")
write.table(
  seuratT_markers_all,
  file = paste0(basedir, "pericarditis_allmerged_Tcells_0.25_markerGenes.txt"),
  row.names = FALSE,
  quote = FALSE,
  sep = "\t"
)

```

# Remove contaminations
```{r}

# Remove cluster 7 (ILCs)
# Remove cluster 9 (B cells)
# Remove cluster 10 (thymocytes)

# Exclude specific clusters
seuratT <- subset(seuratT, RNA_snn_res.0.25 %in% c(7, 9, 10), invert=TRUE)
dim(seuratT) 
```

# Rerun normalization
```{r}
seuratT <- NormalizeData(object = seuratT)
seuratT <- FindVariableFeatures(object = seuratT)
seuratT <- ScaleData(object = seuratT, verbose = FALSE)
seuratT <- RunPCA(object=seuratT, npcs=30, verbose = FALSE)
seuratT <- RunTSNE(object = seuratT, reduction = "pca", dims=1:20)
seuratT <- RunUMAP(object = seuratT, reduction = "pca", dims = 1:20)
seuratT <- FindNeighbors(object = seuratT, reduction = "pca", dims = 1:20)
res <- c(0.1, 0.2, 0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratT <-FindClusters(object = seuratT, resolution = res[i],
                        random.seed = 1234)
}
```


## DimPlot Clusters {.tabset}

### Resolution 0.1
```{r}
Idents(seuratT) <-  seuratT$RNA_snn_res.0.1
DimPlot(seuratT, reduction = "umap", label = T)
```

### Resolution 0.2
```{r}
Idents(seuratT) <-  seuratT$RNA_snn_res.0.2
DimPlot(seuratT, reduction = "umap", label = T)
```

### Resolution 0.25
```{r}
Idents(seuratT) <-  seuratT$RNA_snn_res.0.25
DimPlot(seuratT, reduction = "umap", label = T)
```


# Save seurat object
```{r}
#Save seurat object
basedir <- here()
saveRDS(seuratT, file = paste0(basedir, "/data/pericarditis_allmerged_Tcells_cleaned_seurat.rds"))
```

# Session info
```{r}
sessionInfo()
date()
```

