---
title: "Assign metadata"
author: "Nadine"
date: "2025-04-09"
output: 
html_document:
  self_contained: no
  code_folding: show
  number_sections: no
  toc: yes
  toc_depth: 3
  toc_float: true
  collapsed: no
  smooth_scroll: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

#Load packages
```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(reshape2)
  library(ggplot2)
  library(cowplot)
  library(purrr)
  library(Seurat)
  library(tidyverse)
  library(ggpubr)
  library(runSeurat3)
  library(here)
  library(ggsci)
  library(pheatmap)
  library(scater)
})
```

#Load seurat object
```{r}
#Load merged seurat object (from previous analysis)
basedir<- here()
fileNam <- paste0(basedir, "/data/pericarditis_allmerged_seurat.rds")
seuratM <- readRDS(fileNam)
```

#Metrics
```{r}
dim(seuratM)
table(seuratM$dataset)
```

#Assign meta slots

##Assign short sample name
```{r}
#Assign short name for individual samples
seuratM$SampleName <- "SampleName"

#4wk Controls
seuratM$SampleName[which(seuratM$dataset ==  "318801_02-3_20230516_Mu_4wk_FSC_and_immune_LM3")] <- "4w_LMC1"
seuratM$SampleName[which(seuratM$dataset ==  "318801_04-5_20230516_Mu_4wk_FSC_and_immune_LM4")] <- "4w_LMC2"
seuratM$SampleName[which(seuratM$dataset ==  "372561_02-2_20241128_Mu_LM1_pericard_4w")] <- "4w_LMC3"
seuratM$SampleName[which(seuratM$dataset ==  "372561_05-5_20241128_Mu_LM2_pericard_4w")] <- "4w_LMC4"

#4wk TCRM
seuratM$SampleName[which(seuratM$dataset ==  "318801_03-4_20230516_Mu_4wk_FSC_and_immune_TCRM1")] <- "4w_TCRM1"
seuratM$SampleName[which(seuratM$dataset ==  "318801_05-6_20230516_Mu_4wk_FSC_and_immune_TCRM2")] <- "4w_TCRM2"
seuratM$SampleName[which(seuratM$dataset ==  "318801_06-7_20230516_Mu_4wk_FSC_and_immune_TCRM3")] <- "4w_TCRM3"
seuratM$SampleName[which(seuratM$dataset ==  "318801_07-8_20230516_Mu_4wk_FSC_and_immune_TCRM4")] <- "4w_TCRM4"
seuratM$SampleName[which(seuratM$dataset ==  "372561_01-1_20241128_Mu_TCRM1_pericard_4wk")] <- "4w_TCRM5"
seuratM$SampleName[which(seuratM$dataset ==  "372561_03-3_20241128_Mu_TCRM2_pericard_4wk")] <- "4w_TCRM6"
seuratM$SampleName[which(seuratM$dataset ==  "372561_04-4_20241128_Mu_TCRM3_pericard_4wk")] <- "4w_TCRM7"

#8wk Controls
seuratM$SampleName[which(seuratM$dataset ==  "o310951_08-8_20230302_Mu_FSC_and_immune_LM1")] <- "8w_LMC1"
seuratM$SampleName[which(seuratM$dataset ==  "o310951_09-9_20230302_Mu_FSC_and_immune_LM2")] <- "8w_LMC2"
seuratM$SampleName[which(seuratM$dataset ==  "o310951_12-12_20230302_Mu_FSC_and_immune_LM3")] <- "8w_LMC3"
seuratM$SampleName[which(seuratM$dataset ==  "o310951_14-14_20230302_Mu_FSC_and_immune_LM4")] <- "8w_LMC4"
seuratM$SampleName[which(seuratM$dataset ==  "380131_13-13_20250311_Mu_LM1_pericard_8wk")] <- "8w_LMC5"
seuratM$SampleName[which(seuratM$dataset ==  "380131_14-14_20250311_Mu_LM2_pericard_8wk")] <- "8w_LMC6"
seuratM$SampleName[which(seuratM$dataset ==  "380131_15-15_20250311_Mu_LM3_pericard_8wk")] <- "8w_LMC7"
seuratM$SampleName[which(seuratM$dataset ==  "380131_16-16_20250311_Mu_LM4_pericard_8wk")] <- "8w_LMC8"

#8wk TCRM
seuratM$SampleName[which(seuratM$dataset ==  "o310951_15-15_20230302_Mu_FSC_and_immune_TCRM4")] <- "8w_TCRM1"
seuratM$SampleName[which(seuratM$dataset ==  "398101_6-6_20250912_Mu_TCRM3_pericard_8wk")] <- "8w_TCRM2"
seuratM$SampleName[which(seuratM$dataset ==  "398101_4-4_20250912_Mu_TCRM1_pericard_8wk")] <- "8w_TCRM3"
seuratM$SampleName[which(seuratM$dataset ==  "398101_5-5_20250912_Mu_TCRM2_pericard_8wk")] <- "8w_TCRM4"
seuratM$SampleName[which(seuratM$dataset ==  "380131_17-17_20250311_Mu_TCRM1_CCL19_pericard_8wk")] <- "8w_TCRM5"
seuratM$SampleName[which(seuratM$dataset ==  "380131_18-18_20250311_Mu_TCRM2_CCL19_pericard_8wk")] <- "8w_TCRM6"
seuratM$SampleName[which(seuratM$dataset ==  "380131_19-19_20250311_Mu_TCRM3_CCL19_pericard_8wk")] <- "8w_TCRM7"
seuratM$SampleName[which(seuratM$dataset ==  "380131_20-20_20250311_Mu_TCRM4_CCL19_pericard_8wk")] <- "8w_TCRM8"


table(seuratM$SampleName)

```


##Assign condition
```{r}
#Assign conditions
seuratM$cond <- "TCRM"
seuratM$cond[which(seuratM$SampleName %in% c("4w_LMC1", "4w_LMC2", "4w_LMC3", "4w_LMC4", "8w_LMC1", "8w_LMC2", "8w_LMC3", "8w_LMC4", "8w_LMC5", "8w_LMC6", "8w_LMC7", "8w_LMC8"))] <- "LMC"

table(seuratM$cond)
```

##Assign age of mouse
```{r}
seuratM$age <- "8wk"
seuratM$age[which(seuratM$SampleName %in% c("4w_LMC1", "4w_LMC2", "4w_LMC3", "4w_LMC4", "4w_TCRM1", "4w_TCRM2", "4w_TCRM3", "4w_TCRM4", "4w_TCRM5", "4w_TCRM6", "4w_TCRM7"))] <- "4wk"

table(seuratM$age)
```


##Assign Phenotype
```{r}
#Assign phenotype (based on echocardiography)
##healthy = Controls
##inflamed = EF>50
##iCMP = EF=30-50
##DCM = EF<30

seuratM$Phenotype <- "Phenotype"

#4wk Controls
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_LMC1")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_LMC2")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_LMC3")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_LMC4")] <- "healthy"

#4wk TCRM
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM1")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM2")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM3")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM4")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM5")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM6")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "4w_TCRM7")] <- "inflamed"

#8wk Controls
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC1")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC2")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC3")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC4")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC5")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC6")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC7")] <- "healthy"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_LMC8")] <- "healthy"

#8wk TCRM
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM1")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM2")] <- "iCMP"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM3")] <- "iCMP"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM4")] <- "iCMP"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM5")] <- "iCMP"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM6")] <- "iCMP"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM7")] <- "inflamed"
seuratM$Phenotype[which(seuratM$SampleName ==  "8w_TCRM8")] <- "inflamed"


table(seuratM$Phenotype)

```


#Save seurat object
```{r}
#Save seurat object
basedir <- here()
saveRDS(seuratM, file = paste0(basedir, "/data/pericarditis_allmerged_seurat.rds"))
```


#Session info
```{r}
sessionInfo()
```

