---
title: "data cleanup"
author: "Nadine"
date: "2025-04-09"
output: 
html_document:
  self_contained: no
  code_folding: show
  number_sections: no
  toc: yes
  toc_depth: 3
  toc_float: true
  collapsed: no
  smooth_scroll: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```


#Load packages
```{r}
library(Seurat)
library(ggpubr)
library(ggplot2)
library(here)
```


#Load seurat object
```{r}
## Load merged object from previous analysis
basedir<- here()
fileNam <- paste0(basedir, "/data/pericarditis_allmerged_seurat.rds")
seuratM <- readRDS(fileNam)
```

#define color palette
```{r}
colPal <- c("#355C7D","#B0E0E6","#725663","#84AD83","#868686","#2A363B","#458B74","#CD4F39","#B1746F","#8B668B","#8B3A3A","#628395","#B09C85","#CDB79E","#E9967A","#8491B4","#9B2F5F","#904D39","#4E5A4C","#53354A","#202547","#006400","#00A087","#CDC673","#8968CD","#CDCD00","#FF847C","#DC9989","#F8B195","#9ACD32","#FF7F24","#708090","#AB82FF","#800000","#5CACEE","#7CCD7C","#FFC0CB","#EE9A00","#91D1C2","#D33B44","#104E8B" 
)
```

```{r}
dim(seuratM)
table(seuratM$RNA_snn_res.0.4)
table(seuratM$RNA_snn_res.0.25)

```


#clustering
```{r}
Idents(seuratM) <-  seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap", cols=colPal, label = T)
```

#Abundance across individual samples
```{r abundance plot}
#Plot abundance of clusters in individual samples
datList <- NULL
for(con in unique(seuratM$SampleName)){
  seuratMSub <- subset(seuratM, SampleName==con)
  print(dim(seuratMSub))
  dat_SampleName <- as.data.frame(table(seuratMSub$RNA_snn_res.0.25)) %>%
  mutate(percent=Freq/ncol(seuratMSub)) %>% mutate(SampleName=con)
  datList[[con]] <- dat_SampleName
}
dat_all <- do.call("rbind", datList)

##Barplot with samples on x axis
ggbarplot(dat_all, x= "SampleName", y= "percent", fill = "Var1", legend = "right", legend.titel = "cluster", ylab = "frequency") +  scale_fill_manual(values = colPal) + theme(axis.text.x = element_text(angle = 90))



```


#Marker genes per cluster
```{r}
#Set identity to resolution 0.25
Idents(seuratM) <-  seuratM$RNA_snn_res.0.25

#Run Marker Genes
seuratM_markers_all <- FindAllMarkers(object = seuratM, assay ="RNA",
                                     only.pos = TRUE, min.pct = 0.25,
                                     logfc.threshold = 0.25,
                                     test.use = "wilcox")

#Save Marker Genes as Text File
basedir<- here()
basedir <- paste0(basedir, "/docs/")
write.table(
  seuratM_markers_all,
  file = paste0(basedir, "pericarditis_allmerged_0.25_markerGenes.txt"),
  row.names = FALSE,
  quote = FALSE,
  sep = "\t"
)

```


#Quality check & read counts
```{r}
#Convert seurat object into sce object
sce <- as.SingleCellExperiment(seuratM)


# Function to create histograms per cluster
plotQC_perCluster <- function(sce, feature) {
  df <- as.data.frame(sce@colData)
  clusters <- unique(df$RNA_snn_res.0.25)  # get all clusters
  
  plots <- list()
  
  for (cl in clusters) {
    df_cl <- df[df$RNA_snn_res.0.25 == cl, ]
    
    p <- gghistogram(df_cl,
                     x = feature,
                     bins = 70,
                     fill = "#4682B4",
                     color = "#000000",
                     add_density = TRUE,
                     y = "..density..") +
      ggtitle(paste("Cluster", cl))
    
    plots[[as.character(cl)]] <- p
  }
  
  return(plots)
}

# Example usage
plots_total <- plotQC_perCluster(sce, "total")
plots_detected <- plotQC_perCluster(sce, "detected")

# To display a specific cluster histogram, e.g., cluster 0
#plots_total[["0"]]
#plots_detected[["0"]]

# Or loop to display all
for(p in plots_total) print(p)

```



#Feature plot
```{r}
#genes <- data.frame(gene=rownames(seuratM))

genes_sel <- c(
  "ENSMUSG00000001506.Col1a1",
  "ENSMUSG00000028583.Pdpn",
  "ENSMUSG00000026395.Ptprc",
  "ENSMUSG00000032093.Cd3e",
  "ENSMUSG00000030724.Cd19",
  "ENSMUSG00000030786.Itgam",
  "ENSMUSG00000063011.Msln",
  "ENSMUSG00000031004.Mki67"

)


plots <- lapply(genes_sel, function(gene) {
  FeaturePlot(
    object = seuratM,
    features = gene,
    cols = c("#C1CDCD", "#800000"),
    reduction = "umap"
  )
})

for (p in plots) print(p)


```


#Filtering
```{r}
#remove cluster 4 due to low gene count
#remove cluster 9 due to high gene count (doublets)
#remove cluster 14 contaminating cardiomyocytes
dim(seuratM)
seuratMSub <- subset(seuratM, RNA_snn_res.0.25 %in% c(4,9, 14), invert=TRUE)
dim(seuratMSub)

```

#Rerun normmalization on filtered seurat object
```{r}
seuratMSub <- NormalizeData(object = seuratMSub)
seuratMSub <- FindVariableFeatures(object = seuratMSub)
seuratMSub <- ScaleData(object = seuratMSub, verbose = FALSE)
seuratMSub <- RunPCA(object=seuratMSub, npcs=30, verbose = FALSE)
seuratMSub <- RunTSNE(object = seuratMSub, reduction = "pca", dims=1:20)
seuratMSub <- RunUMAP(object = seuratMSub, reduction = "pca", dims = 1:20)
seuratMSub <- FindNeighbors(object = seuratMSub, reduction = "pca", dims = 1:20)
res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratMSub <-FindClusters(object = seuratMSub, resolution = res[i],
                        random.seed = 1234)
}


```


#Clustering
```{r}
Idents(seuratMSub) <-  seuratMSub$RNA_snn_res.0.25
DimPlot(seuratMSub, reduction = "umap", cols=colPal, label = T)
```


#Save seurat object
```{r}
#Save seurat object
basedir <- here()
saveRDS(seuratMSub, file = paste0(basedir, "/data/pericarditis_allmerged_cleaned_seurat.rds"))
```

#Session info
```{r}
sessionInfo()
```

