---

title: "6_Subset FBs"
author: "Nadine"
date: "2025-04-09"
output: 
html_document:
  self_contained: no
  code_folding: show
  number_sections: no
  toc: yes
  toc_depth: 3
  toc_float: true
  collapsed: no
  smooth_scroll: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

#Load packages
```{r}
suppressPackageStartupMessages({
  library(ExploreSCdataSeurat3)
  library(runSeurat3)
  library(Seurat)
  library(ggpubr)
  library(pheatmap)
  library(SingleCellExperiment)
  library(dplyr)
  library(tidyverse)
  library(viridis)
  library(muscat)
  library(circlize)
  library(destiny)
  library(scater)
  library(metap)
  library(multtest)
  library(clusterProfiler)
  library(org.Mm.eg.db)
  library(msigdbr)
  library(enrichplot)
  library(DOSE)
  library(grid)
  library(gridExtra)
  library(ggupset)
  library(VennDiagram)
  library(reshape2)
  library(ggplot2)
  library(cowplot)
  library(purrr)
  library(here)
  library(ggsci)
  library(RColorBrewer)
  library(ggrepel)
})
```


#Load seurat object
```{r}
## load merged and cleaned object from previous analysis
basedir<- here()
fileNam <- paste0(basedir, "/data/pericarditis_allmerged_cleaned_cL_seurat.rds")
seuratM <- readRDS(fileNam)
```

#Subset FBs
```{r}

unique(seuratM$clusterLabel)
Idents(seuratM) <- seuratM$clusterLabel
dim(seuratM)
seuratMSub <- subset(seuratM, idents = c("Fibroblasts-1", "Fibroblasts-2", "Cover cells"))
dim(seuratMSub)

```


#Rerun normalization
```{r}
seuratM <- NormalizeData(object = seuratMSub)
seuratM <- FindVariableFeatures(object = seuratM)
seuratM <- ScaleData(object = seuratM, verbose = FALSE)
seuratM <- RunPCA(object=seuratM, npcs=30, verbose = FALSE)
seuratM <- RunTSNE(object = seuratM, reduction = "pca", dims=1:20)
seuratM <- RunUMAP(object = seuratM, reduction = "pca", dims = 1:20)
seuratM <- FindNeighbors(object = seuratM, reduction = "pca", dims = 1:20)
res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratM <-FindClusters(object = seuratM, resolution = res[i],
                        random.seed = 1234)
}
```

#Visualizaion in umaps
```{r}
Idents(seuratM) <-  seuratM$RNA_snn_res.0.4
DimPlot(seuratM, reduction = "umap", label = T)

Idents(seuratM) <-  seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap", label = T)

```

#Marker genes per cluster
```{r, include = T, eval = T}
#Set identity to resolution 0.25
Idents(seuratM) <-  seuratM$RNA_snn_res.0.25

#Run Marker Genes
seuratM_markers_all <- FindAllMarkers(object = seuratM, assay ="RNA",
                                     only.pos = TRUE, min.pct = 0.25,
                                     logfc.threshold = 0.25,
                                     test.use = "wilcox")

#Save Marker Genes as Text File
basedir<- here()
basedir <- paste0(basedir, "/docs/")
write.table(
  seuratM_markers_all,
  file = paste0(basedir, "pericarditis_allmerged_FB_0.25_markerGenes.txt"),
  row.names = FALSE,
  quote = FALSE,
  sep = "\t"
)

```



#Abundance across individual samples
```{r abundance plot}
#Plot abundance of clusters in individual samples
datList <- NULL
for(con in unique(seuratM$SampleName)){
  seuratMSub <- subset(seuratM, SampleName==con)
  print(dim(seuratMSub))
  dat_SampleName <- as.data.frame(table(seuratMSub$RNA_snn_res.0.25)) %>%
  mutate(percent=Freq/ncol(seuratMSub)) %>% mutate(SampleName=con)
  datList[[con]] <- dat_SampleName
}
dat_all <- do.call("rbind", datList)

##Barplot with samples on x axis
ggbarplot(dat_all, x= "SampleName", y= "percent", fill = "Var1", legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90))



```

#Feature plot
```{r}
#genes <- data.frame(gene=rownames(seuratM))

genes_sel <- c(
  "ENSMUSG00000001506.Col1a1",
  "ENSMUSG00000028583.Pdpn",
  "ENSMUSG00000026395.Ptprc",
  "ENSMUSG00000022878.Adipoq",
  "ENSMUSG00000063011.Msln",
  "ENSMUSG00000062515.Fabp4",
  "ENSMUSG00000042985.Upk3b"

)


plots <- lapply(genes_sel, function(gene) {
  FeaturePlot(
    object = seuratM,
    features = gene,
    cols = c("#C1CDCD", "#800000"),
    reduction = "umap"
  )
})

for (p in plots) print(p)


```

#Remove contaminations
```{r}

table(seuratM$RNA_snn_res.0.25)

#remove cluster 6,8 - immune cells
#remove cluster 10 - mesothelial cells

table(seuratM$orig.ident)

#exclude specific clusters
seuratMSub <- subset(seuratM, RNA_snn_res.0.25 %in% c(6,8,10), invert=TRUE)

table(seuratMSub$orig.ident)

```



#Rerun seurat
```{r}
seuratM <- NormalizeData(object = seuratMSub)
seuratM <- FindVariableFeatures(object = seuratM)
seuratM <- ScaleData(object = seuratM, verbose = FALSE)
seuratM <- RunPCA(object=seuratM, npcs=30, verbose = FALSE)
seuratM <- RunTSNE(object = seuratM, reduction = "pca", dims=1:20)
seuratM <- RunUMAP(object = seuratM, reduction = "pca", dims = 1:20)
seuratM <- FindNeighbors(object = seuratM, reduction = "pca", dims = 1:20)
res <- c(0.25, 0.6, 0.8, 0.4, 0.1, 0.2)
for (i in 1:length(res)) {
  seuratM <-FindClusters(object = seuratM, resolution = res[i],
                        random.seed = 1234)
}
```

#Visualizaion in umaps
```{r}
Idents(seuratM) <-  seuratM$RNA_snn_res.0.2
DimPlot(seuratM, reduction = "umap", label = T)

Idents(seuratM) <-  seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap", label = T)

```
#Save seurat object
```{r}
#Save seurat object
basedir <- here()
saveRDS(seuratM, file = paste0(basedir, "/data/pericarditis_allmerged_FB_cleaned_seurat.rds"))
```



#Session info
```{r}
sessionInfo()
```

