---
title: "IL6 Signaling in Pericardial Fibroblasts"
author: "Nadine"
date: "2026-04-15"
output: 
html_document:
  self_contained: no
  code_folding: show
  number_sections: no
  toc: yes
  toc_depth: 3
  toc_float: true
  collapsed: no
  smooth_scroll: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

# Load packages
```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(Seurat)
  library(here)
  library(pheatmap)
  library(tibble)
})
```


# Load seurat object
```{r}
#Load merged and cleaned object containing FBs
basedir<- here()
fileNam <- paste0(basedir, "/data/pericarditis_allmerged_FB_cleaned_cL_seurat.rds")
seuratFB <- readRDS(fileNam)
```

# Define color palette
```{r}
# Color palette FBclusterLabel
colPal_FB <- c("#C1CDC1", "#EEE8AA", "#556B2F", "#CD6839", "#B2CD5B", "#A2B5CD","#DCA86C", "#6B7F99")
names(colPal_FB) <- c("Fat4 Fibroblasts","Ccl11 Fibroblasts", "Tcf21 Fibroblasts", "Cxcl13 CoverCells", "Ccl19 FRCs", "Bmp4 Fibroblasts", "Col11 Fibroblasts", "Dpp4 Fibroblasts")

# Color palette Phenotypes
colPal_Phenotype <- c("#8B0000", "#FCDACB", "#E6E6E6")
names(colPal_Phenotype) <- c( "iCMP", "inflamed", "healthy")

```


## Violin plots per cluster {.tabset}

### Il6
```{r}
#genes <- data.frame(gene=rownames(seuratFB))
# Gene expression across all cluster
Idents(seuratFB) <- seuratFB$FBclusterLabel

# Set sample order
ordX <- c("Ccl19 FRCs", "Cxcl13 CoverCells", "Dpp4 Fibroblasts", "Ccl11 Fibroblasts", "Fat4 Fibroblasts", "Bmp4 Fibroblasts", "Tcf21 Fibroblasts", "Col11 Fibroblasts")

# Violin plot
VlnPlot(object = seuratFB, features = "ENSMUSG00000025746.Il6", cols = colPal_FB, alpha = 0.05) + scale_x_discrete(limits = ordX)
```

### Il6ra
```{r}
VlnPlot(object = seuratFB, features = "ENSMUSG00000027947.Il6ra", cols = colPal_FB, alpha = 0.05) + scale_x_discrete(limits = ordX)
```

### Il6st
```{r}
VlnPlot(object = seuratFB, features = "ENSMUSG00000021756.Il6st", cols = colPal_FB, alpha = 0.05) + scale_x_discrete(limits = ordX)
```


## Violin plots split by condition {.tabset}

### Il6
```{r}
VlnPlot(object = seuratFB, features = "ENSMUSG00000025746.Il6", cols = c("#D3D3D3", "#B45B5C"), split.by = "cond", split.plot = TRUE, alpha = 0.1) + scale_x_discrete(limits = ordX)
```

### Il6ra
```{r}
VlnPlot(object = seuratFB, features = "ENSMUSG00000027947.Il6ra", cols = c("#D3D3D3", "#B45B5C"), split.by = "cond", split.plot = TRUE, alpha = 0.1) + scale_x_discrete(limits = ordX)
```

### Il6st
```{r}
VlnPlot(object = seuratFB, features = "ENSMUSG00000021756.Il6st", cols = c("#D3D3D3", "#B45B5C"), split.by = "cond", split.plot = TRUE, alpha = 0.1) + scale_x_discrete(limits = ordX)
```


# Session info
```{r}
sessionInfo()
date()
```


