---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


## Pericardial Cells

### Pericardial Cells TCRM and Ctrl
Pericardial Cells TCRM and Ctrl
[link](4_characterize-full-dataset.html)

### IL6 Signaling in Pericardial Cells
IL6 Signaling in Pericardial Cells
[link](5_IL6-full-dataset.html)


## Pericardial Fibroblasts

### Subset Pericardial Fibroblasts
Subset Pericardial Fibroblasts
[link](6_Subset-FBs.html)

### Pericardial Fibroblasts TCRM and Ctrl
Pericardial Fibroblasts TCRM and Ctrl
[link](7_characterize-FBs.html)

### Pericardial FALC FRCs TCRM and Ctrl
Pericardial FALC FRCs TCRM and Ctrl
[link](8_FRC-Ctrl-vs-TCRM.html)

### IL6 Signaling in Pericardial Fibroblasts
IL6 Signaling in Pericardial Fibroblasts
[link](9_IL6-FBs.html)


## Pericardial T cells

### Subset Pericardial T cells
Subset Pericardial T Cells
[link](10_subset-T-cells.html)

### Pericardial T cells TCRM and Ctrl
Pericardial T Cells TCRM and Ctrl
[link](11_characterize-T-cells.html)


## Interaction Analysis

### CellChat Pericardial Cells
CellChat Pericardial Cells
[link](12_cellchat-TCRM-vs-Ctrl.html)

### Cellchat T cells and Fibroblasts
Cellchat T cells and Fibroblasts
[link](13_cellchat-T-FB-merge.html)
